apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-deployment-example
  namespace: namespacedemo
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-deployment-example-prod
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  labels:
                    app: my-application-web
                  name: my-application-web
                spec:
                  replicas: 1
                  selector:
                    matchLabels:
                      app: my-application-web
                  template:
                    metadata:
                      labels:
                        app: my-application-web
                    spec:
                      containers:
                        - image: 'quay.io/<username>/my-application-nginx:latest'
                          name: my-application-nginx
                          imagePullPolicy: Always
                          ports:
                            - containerPort: 8443
                              protocol: TCP
                          livenessProbe:
                            exec:
                              command:
                                - /bin/sh
                                - '-c'
                                - '[ -f /run/nginx.pid ] && ps -A | grep nginx'
                            initialDelaySeconds: 10
                            periodSeconds: 5
                          readinessProbe:
                            httpGet:
                              scheme: HTTPS
                              path: /index.html
                              port: 8443
                            initialDelaySeconds: 10
                            periodSeconds: 5
                        - image: 'quay.io/<username>/my-application-app-server:latest'
                          name: my-application-app-server
                          imagePullPolicy: Always
                          ports:
                            - containerPort: 8080
                              protocol: TCP
                          livenessProbe:
                            exec:
                              command:
                                - /bin/sh
                                - '-c'
                                - /usr/bin/my-application-web --alive
                            initialDelaySeconds: 10
                            periodSeconds: 5
                          readinessProbe:
                            httpGet:
                              scheme: HTTP
                              path: /healthz
                              port: 8080
                            initialDelaySeconds: 10
                            periodSeconds: 5
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  labels:
                    app: my-application-jobs
                  name: my-application-jobs
                spec:
                  replicas: 1
                  selector:
                    matchLabels:
                      app: my-application-jobs
                  template:
                    metadata:
                      labels:
                        app: my-application-jobs
                    spec:
                      containers:
                        - image: 'quay.io/<username>/my-application-jobs:latest'
                          name: my-application-jobs
                          imagePullPolicy: Always
                          livenessProbe:
                            exec:
                              command:
                                - /bin/sh
                                - '-c'
                                - /usr/bin/my-application-jobs --alive
                            initialDelaySeconds: 10
                            periodSeconds: 5
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-deployment-example
  namespace: namespacedemo
placementRef:
  name: placement-policy-deployment-example
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-deployment-example
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-deployment-example
  namespace: namespacedemo
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchLabels:
      name: local-cluster
      monitoring: true

