apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-ldap-sample
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
     - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-ldap
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OAuth
                metadata:
                  name: cluster
                spec:
                  identityProviders:
                    - ldap:
                        attributes:
                          email:
                            - mail
                          id:
                            - dn
                          name:
                            - cn
                          preferredUsername:
                            - uid
                        bindDN: 'cn=admin,dc=planetexpress,dc=com'
                        bindPassword:
                          name: ldap-bind-password
                        insecure: true
                        url: >-
                          ldap://ldap.cluster.lab.com/DC=planetexpress,DC=com?uid?sub?(memberOf=cn=admin_staff,ou=people,dc=planetexpress,dc=com)
                      mappingMethod: claim
                      name: ldap
                      type: LDAP
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-ldap-sample
placementRef:
  name: placement-ldap-sample
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-ldap-sample
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-ldap-sample
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: In, values: ["true"]}

