apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-htpasswd-ldap-sample
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-secret-2
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                data:
                  htpasswd: >-
                    dXNlcjE6JDJ5JDA1JFBqUWVqZ1VNMzU5LnJkOE5xQzlweXVHbk9JM3JrVWl4cWh2NDg4enJVNVJvaEhZa2dLWGFhCnVzZXIyOiQyeSQwNSRQalFlamdVTTM1OS5yZDhOcUM5cHl1R25PSTNya1VpeHFodjQ4OHpyVTVSb2hIWWtnS1hhYQp1c2VyMzokMnkkMDUkUGpRZWpnVU0zNTkucmQ4TnFDOXB5dUduT0kzcmtVaXhxaHY0ODh6clU1Um9oSFlrZ0tYYWEKdXNlcjQ6JDJ5JDA1JFBqUWVqZ1VNMzU5LnJkOE5xQzlweXVHbk9JM3JrVWl4cWh2NDg4enJVNVJvaEhZa2dLWGFhCnVzZXI1OiQyeSQwNSRQalFlamdVTTM1OS5yZDhOcUM5cHl1R25PSTNya1VpeHFodjQ4OHpyVTVSb2hIWWtnS1hhYQ==
                kind: Secret
                metadata:
                  name: htpass-secret
                  namespace: openshift-config
                type: Opaque
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-htpasswd-ldap
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OAuth
                metadata:
                  name: cluster
                spec:
                  identityProviders:
                    - name: my_identity_provider
                      mappingMethod: claim
                      type: HTPasswd
                      htpasswd:
                        fileData:
                          name: htpass-secret
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OAuth
                metadata:
                  name: cluster
                spec:
                  identityProviders:
                    - ldap:
                        attributes:
                          email:
                            - mail
                          id:
                            - dn
                          name:
                            - cn
                          preferredUsername:
                            - uid
                        bindDN: 'cn=admin,dc=planetexpress,dc=com'
                        bindPassword:
                          name: ldap-bind-password
                        insecure: true
                        url: >-
                          ldap://ldap.cluster.lab.com/DC=planetexpress,DC=com?uid?sub?(memberOf=cn=admin_staff,ou=people,dc=planetexpress,dc=com)
                      mappingMethod: claim
                      name: ldap
                      type: LDAP
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-htpasswd-ldap-sample
placementRef:
  name: placement-htpasswd-sample
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-htpasswd-ldap-sample
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-htpasswd-ldap-sample
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: In, values: ["true"]}

